name: ynoa-hosting

services:
  directus:
    image: directus/directus:11.10.0
    ports:
      - ${DIRECTUS_PORT}:8055
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./data:/directus/data
    env_file:
      - ./.env
